on:
  push:
    branches:
      - main


jobs:
  test-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Tox
        run: pip install tox
      - name: Run default tests
        run: tox run -e default